name: Build and Push Docker Image

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Lint"]
    branches:
        - main
    types:
        - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: docker/build-push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gabrieru/portfolio:latest
